blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('',views.indexView,name='index'),
    path('detail/<int:blog_id>/',views.detailView,name='detail'),
    path('add/',views.create_blog,name='create_blog')
    ]

gaana/urls.py
from django.urls import path
from . import views
app_name='gaana'
urlpatterns = [
    path('',views.indexView,name='index'),
    path('detail/<int:album_id>/',views.detailView,name='detail'),
    path('album/add/',views.albumCreate,name='create_album'),
    path('album/favourite/<int:album_id>/',views.favouriteAlbum,name='album_favourite'),
    path('song/<str:filter_by>/',views.song,name='songs'),
    path('song/add/<int:album_id>',views.songCreate,name='create_song'),
    path('song/favourite/<int:song_id>/',views.favouriteSong,name='song_favourite'),
    path('album/<int:album_id>/delete_album/',views.deleteAlbum,name='delete_album'),
    path('song/<int:album_id>/delete_song/<int:song_id>/',views.deleteSong,name='delete_song'),
    path('register/',views.register,name='register'),
    path('login_user/',views.login_user,name='login_user'),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('lyrics/<int:song_id>', views.lyrics,name='lyrics')
]

music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from gaana import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homeView,name='home'),
    path('gaana/', include('gaana.urls')),
    path('blog/',include('blog.urls')),
    path('hots/',include('hots.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gaana/models.py
from django.db import models
from django.contrib.auth.models import Permission,User

# Create your models here.
class Album(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    artist=models.CharField(max_length=100)
    album_title=models.CharField(max_length=200)
    genre=models.CharField(max_length=100)
    album_logo=models.FileField()
    is_favorite=models.BooleanField(default=False)
    def __str__(self):
        return self.album_title+'-'+self.artist

class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    song_title=models.CharField(max_length=100)
    audio_file=models.FileField(default='')
    is_favorite=models.BooleanField(default=False)
    lyrics=models.TextField(max_length=50000, default='')
    def __str__(self):
        return self.song_title

gaana/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Album,Song

class AlbumForm(forms.ModelForm):
    class Meta:
        model=Album
        fields=['artist','album_title','genre','album_logo']

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['song_title', 'audio_file','lyrics']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    #so that form field dont show character instead show dots
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

gaana/views.py
#from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.db.models import Q
from .models import Album,Song
from .forms import UserForm,SongForm,AlbumForm
#from django.core.mail import send_mail
#from django.conf import settings
#from django.views import generic
#from django.views.generic.edit import CreateView,UpdateView,DeleteView
#from django.views.generic import View
#from django.core.urlresolvers import reverse_lazy

AUDIO_FILE_TYPES=['wav','mp3','ogg']
IMAGE_FILE_TYPES=['png','jpg','jpeg']

def homeView(request):
    return render(request,'gaana/home.html')

def indexView(request):
    if not request.user.is_authenticated:
        return render(request,'gaana/login.html')
    else:
        all_album=Album.objects.filter(user=request.user)
        song_results=Song.objects.all()
        query=request.GET.get('q')
        if query:
            all_album=all_album.filter(Q(album_title__icontains=query) | Q(artist__icontains=query)).distinct()
            song_results=song_results.filter(Q(song_title__icontains=query)).distinct()
            return render(request,'gaana/index.html',{'all_album':all_album,'songs':song_results})
        else:
            return render(request,'gaana/index.html',{'all_album':all_album})


def detailView(request,album_id):
    if not request.user.is_authenticated:
        return render(request,'gaana/login.html')
    else:
        user=request.user
        album=get_object_or_404(Album,pk=album_id)                                  #work same as try except(
        return render(request,'gaana/detail.html',{'album':album,'user':user})      #try:
                                                                                    #album=Album.objects.get(pk=album_id)
                                                                                    #except Album.DoesNotExist:
                                                                                    #raise Http404('Does Not Exist'))
def albumCreate(request):
    if not request.user.is_authenticated:
        return render(request,'gaana/login.html')
    else:
        form=AlbumForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            album=form.save(commit=False)
            album.user=request.user
            album.album_logo=request.FILES['album_logo']
            file_type=album.album_logo.url.split('.')[-1]
            file_type=file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context={'album':album,'form':form,'error_message':'Image file must be PNG,JPG or JPEG'}
                return render(request,'gaana/create_album.html',context)
            else:
                album.save()
                return render(request,'gaana/detail.html',{'album':album})
        else:
            return render(request,'gaana/create_album.html',{'form':form})


def favouriteAlbum(request,album_id):
    album=get_object_or_404(Album,pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite=False
        else:
            album.is_favorite=True
        album.save()
    except (KeyError,album.DoesNotExist):
        return JsonResponse({'success':False})
    else:
        return JsonResponse({'success':True})


def song(request,filter_by):
    if not request.user.is_authenticated:
        return render(request,'gaana/login.html')
    else:
        try:
            song_ids=[]
            for album in Album.objects.filter(user=request.user):
                for songs in album.song_set.all():                          #remember: for songs in Album.song_set.all():
                    song_ids.append(songs.pk)
            user_songs=Song.objects.filter(pk__in=song_ids)
            if filter_by=='favorites':
                user_songs=user_songs.filter(is_favorite=True)              #not user_songs.objects.filter(is_favorite=True)
        except Album.DoesNotExist:
            user_songs=[]
        return render(request,'gaana/songs.html',{'song_list':user_songs,'filter_by':filter_by})


def songCreate(request,album_id):
    form=SongForm(request.POST or None, request.FILES or None)
    album=get_object_or_404(Album,pk=album_id)
    if form.is_valid():
        album_songs=album.song_set.all()
        for s in album_songs:
            if s.song_title==form.cleaned_data.get("song_title"):
                context={'album':album,'form':form,'error_message':'You already added that song'}
                return render(request,'gaana/create_song.html',context)
        song=form.save(commit=False)
        song.album=album
        song.audio_file=request.FILES['audio_file']
        file_type=song.audio_file.url.split('.')[-1]
        file_type=file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context={'album':album,'form':form,'error_message':'Audio file must be WAV,MP3,OGG'}
            return render(request,'gaana/create_song.html',context)
        song.save()
        return render(request,'gaana/detail.html',{'album':album})
    return render(request,'gaana/create_song.html',{'album':album,'form':form})
#need to sent from as model defined


def favouriteSong(request,song_id):
    song=get_object_or_404(Song,pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite=False
        else:
            song.is_favorite=True
        song.save()
    except(KeyError,song.DoesNotExist):
        return JsonResponse({'success':False})
    else:
        return JsonResponse({'success':True})

def lyrics(request,song_id):
    song=get_object_or_404(Song,pk=song_id)
    return render(request,'gaana/lyrics.html',{'song':song})

def deleteAlbum(request,album_id):
    album=Album.objects.get(pk=album_id)
    album.delete()
    all_album=Album.objects.filter(user=request.user)
    return render(request,'gaana/index.html',{'all_album':all_album})


def deleteSong(request,album_id,song_id):
    album=get_object_or_404(Album,pk=album_id)
    song=Song.objects.get(pk=song_id)
    song.delete()
    return render(request,'gaana/detail.html',{'album':album})


def register(request):
    form=UserForm(request.POST or None)
    if form.is_valid():
        user=form.save(commit=False)
        username=form.cleaned_data['username']
        password=form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user=authenticate(username=username,password=password)
        if user is not None:
                if user.is_active:
                    login(request,user)
                    all_album=Album.objects.filter(user=request.user)
                    return render(request,'gaana/index.html',{'all_album':all_album})
        return render(request,'gaana/register.html',{'form':form})
    else:
        return render(request,'gaana/register.html',{'form':form})

def login_user(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                all_album=Album.objects.filter(user=request.user)
                return render(request,'gaana/index.html',{'all_album':all_album})
            else:
                return render(request,'gaana/login.html',{'error_message':'Your account has been disabled'})
        else:
            return render(request, 'gaana/login.html', {'error_message': 'Invalid login'})
    return render(request, 'gaana/login.html')


def logout_user(request):
    logout(request)
    form=UserForm(request.POST or None)
    return render(request,'gaana/login.html',{'form':form})





'''
def index(request):
    all_album=Album.objects.all()
    context={'all_album':all_album}
    return render(request,'index.html',context)
class indexView(generic.ListView):
    template_name = 'gaana/index.html'
    content_object_name = 'all_albums' #otherwse ll take object name as all_objects not all_albums
    def query_set(self):
        return Album.objects.all()

class detailView(generic.DetailView):
    model=Album #specific to album with pk
    template_name = 'gaana/detail.html'

class AlbumCreate(CreateView):
    model=Album
    fields=['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model=Album
    fields=['artist','album_title','genre','album_logo']

class AlbumDelete(DeleteView):
    model=Album
    success_url=reverse_lazy('gaana:index')

class UserFormView(View):
    form_class=UserForm #blueprint we want
    template_name='gaana/registration_form.html'

    #display blank form
    def get(self,request):
        form=self.form_class(None)q
        return render(request,self.template_name,{'form': form})

    #process form data
    #all data get stored in request.POST and  django forms validate data issef(in forms.py)
    def post(self,request):
        form=self.form_class(request.POST)

        if form.is_valid():
            user=form.save(commint=False)#just store data not in database

            #cleaned (normalized) data ie same formal eg date
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
'''

gaana/templates/gaana/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}afreen{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'gaana/style.css' %}"/> {#include ot after bootstrap otherwise we wont able to overwrite#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'gaana/js/main.js' %}"></script>
<style>
.header {

    text-align: center;
    background: #000000;
}
.navbar
{
    margin-bottom: 0px;
}
.footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color:#080808b0;
   color: white;
   text-align: center;
}
</style>
</head>
<body>
{% load staticfiles%}
        <div class="header">
        <img src="{% static "gaana/images/logo5.jpg"%}">
        </div>
<nav class="navbar navbar-inverse"  style="background:#080808;">
    <div class="container-fluid">
        <!-- Header  here data-target is to target element ie where to use toggle button-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">afreen</a>
        </div>

        <!-- Items id since here we gonna use data-target feature and album_active block is for highlighing working page-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}" ><a href="{% url 'gaana:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'gaana:songs' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'gaana:index' %}" id="navBarSearchForm">
                <div class="form-group">
                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
              <button type="submit" class="btn btn-default" style="background:#080808; color:#ccc ">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'gaana:create_album' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="{% url 'gaana:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
<br>
{% block body %}
{% endblock %}
<div class="footer">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 f-desc padding-10px">
  <audio controls="" preload="none">
  <source src="" type="audio/mpeg">
  </audio>
  </div>
</div>
</body>
</html>

gaana/templates/gaana/create_song.html
{% extends 'gaana/base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default" style="background-color:#080808b0; color:#e1d3c1 ">
                <div class="panel-body">
                        <a href="{% url 'gaana:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'gaana:detail' album.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'gaana:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default" style="background-color:#080808b0; color:#e1d3c1 ">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'gaana/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

gaana/templates/gaana/detail.html
{% extends 'gaana/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default" style="background-color:#080808b0; color:#e1d3c1">
                <div class="panel-body">
                    <a href="{% url 'gaana:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'gaana:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'gaana:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default"style="background-color:#080808b0; color:#e1d3c1">
                <div class="panel-body" >

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Lyrics</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                  <a href="{% url 'gaana:lyrics' song.id %}"> Click Here</a></td>
                                <td>
                                    <a href="{% url 'gaana:song_favourite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'gaana:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

gaana/templates/gaana/index.html
{% extends 'gaana/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12" style="color:#fff">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if all_album %}
            {% for album in all_album %}
                <div class="col-sm-4 col-lg-4">
                    <div class="thumbnail" style="background-color:#080808b0; color:#e1d3c1">
                        <a href="{% url 'gaana:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption" style="background-color:#080808b0; color:#e1d3c1">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'gaana:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'gaana:delete_album' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="{% url 'gaana:album_favourite' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'gaana:create_album' %}">
                    <button type="button" class="btn btn-success" style="background-color:#080808; border-color:#080808">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default" style="background-color:#080808b0; color:#e1d3c1">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Lyrics</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                          <a href="{% url 'gaana:lyrics' song.id %}"> Click Here</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'gaana:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'gaana:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'gaana:song_favourite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

gaana/templates/gaana/songs.html
{% extends 'gaana/base.html' %}
{% block title %}All Songs{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'gaana:songs' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'gaana:songs' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default"style="background-color:#080808b0; color:#e1d3c1">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Lyrics</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                      <a href="{% url 'gaana:lyrics' song.id %}"> Click Here</a></td>
                                    <td>
                                        <a href="{% url 'gaana:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'gaana:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'gaana:song_favourite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}