blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('',views.indexView,name='index'),
    path('detail/<int:blog_id>/',views.detailView,name='detail'),
    path('add/',views.create_blog,name='create_blog')
    ]

gaana/urls.py
from django.urls import path
from . import views
app_name='gaana'
urlpatterns = [
    path('',views.indexView,name='index'),
    path('detail/<int:album_id>/',views.detailView,name='detail'),
    path('album/add/',views.albumCreate,name='create_album'),
    path('album/favourite/<int:album_id>/',views.favouriteAlbum,name='album_favourite'),
    path('song/<str:filter_by>/',views.song,name='songs'),
    path('song/add/<int:album_id>',views.songCreate,name='create_song'),
    path('song/favourite/<int:song_id>/',views.favouriteSong,name='song_favourite'),
    path('album/<int:album_id>/delete_album/',views.deleteAlbum,name='delete_album'),
    path('song/<int:album_id>/delete_song/<int:song_id>/',views.deleteSong,name='delete_song'),
    path('register/',views.register,name='register'),
    path('login_user/',views.login_user,name='login_user'),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('lyrics/<int:song_id>', views.lyrics,name='lyrics')
]

hots/urls.py
from django.urls import path
from . import views
#from . import views
app_name='hots'
urlpatterns = [
    path('',views.indexView,name='index'),
    path('details/<int:hots_id>/',views.detailView,name='detail')
    ]

music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from gaana import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homeView,name='home'),
    path('gaana/', include('gaana.urls')),
    path('blog/',include('blog.urls')),
    path('hots/',include('hots.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hots/models.py
from django.db import models
from datetime import date
# Create your models here.

class Hots(models.Model):
    hots_title=models.CharField(max_length=500)
    hots_image=models.FileField()
    description = models.TextField(max_length=20000, help_text="Enter you blog text here.")
    post_date = models.DateField(default=date.today)

    def __str__(self):
        return self.hots_title

hots/__pycache__/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Album,Song

class AlbumForm(forms.ModelForm):
    class Meta:
        model=Album
        fields=['artist','album_title','genre','album_logo']

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    #so that form field dont show character instead show dots
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

hots/views.py
from django.shortcuts import render, get_object_or_404
from .models import Hots


IMAGE_FILE_TYPES=['png','jpg','jpeg']
# Create your views here.
def indexView(request):
    all_hots=Hots.objects.order_by('-post_date')
    return render(request,'hots/index.html',{'all_hots':all_hots})

def detailView(request,hots_id):
    hots=get_object_or_404(Hots,pk=hots_id)
    return render(request,'hots/details.html',{'hots':hots})

hots/templates/hots/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Hots{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" href="{% static 'gaana/style.css' %}"/> {#include ot after bootstrap otherwise we wont able to overwrite#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'gaana/js/main.js' %}"></script>
<style>
.header {

    text-align: center;
    background: #000000;
}
.navbar
{
    margin-bottom: 0px;
}

</style>
</head>
<body style="background:#080808">
{% load staticfiles%}
        <div class="header">
        <img src="{% static "gaana/images/logo5.jpg"%}">
        </div>
<nav class="navbar navbar-inverse"  style="background:#080808;">
    <div class="container-fluid">
        <!-- Header  here data-target is to target element ie where to use toggle button-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">afreen</a>
        </div>

        <!-- Items id since here we gonna use data-target feature and album_active block is for highlighing working page-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}" ><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'hots:index' %}"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp; All Hots</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'gaana:index' %}" id="navBarSearchForm">
                <div class="form-group">
                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
              <button type="submit" class="btn btn-default" style="background:#080808; color:#ccc ">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">

                <li class=""><a href="{% url 'blog:index' %}"><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span>&nbsp;Contact Us</a></li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

hots/templates/hots/details.html
{% extends 'hots/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-4 col-lg-4">
          <div class="panel panel-default" style="background-color:#080808b0; color:#e1d3c1">
              <div class="panel-body">
                  <a href="{% url 'hots:detail' hots.id %}">
                      {% if hots.hots_image %}
                          <img src="{{ hots.hots_image.url }}" class="img-responsive">
                      {% else %}
                          <h3>No image to display</h3>
                      {% endif %}
                  </a>
              </div>
          </div>
      </div>
      <div class="col-sm-8 col-md-8">
          <div class="panel panel-default"style="background-color:#080808b0; color:#e1d3c1">
              <div class="panel-body" >
                <h1>{{ hots.hots_title}}</h1>
                <p>{{hots.description}}</p>
              </div>
            </div>
          </div>
        </div>
  {% endblock %}

hots/templates/hots/index.html
{% extends 'hots/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        {% if all_hots %}
            {% for hots in all_hots %}
                <div class="col-sm-4 col-lg-4">
                    <div class="thumbnail" style="background-color:#080808b0; color:#e1d3c1">
                        <a href="{% url 'hots:detail' hots.id %}">
                            <img src="{{ hots.hots_image.url }}" class="img-responsive">
                        </a>
                        <div class="caption" style="background-color:#080808b0; color:#e1d3c1">
                            <h2>{{ hots.hots_title }}</h2>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'hots:index' %}">
                    <button type="button" class="btn btn-success" style="background-color:#080808; border-color:#080808">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Hots
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}