blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('',views.indexView,name='index'),
    path('detail/<int:blog_id>/',views.detailView,name='detail'),
    path('add/',views.create_blog,name='create_blog')
    ]

gaana/urls.py
from django.urls import path
from . import views
app_name='gaana'
urlpatterns = [
    path('',views.indexView,name='index'),
    path('detail/<int:album_id>/',views.detailView,name='detail'),
    path('album/add/',views.albumCreate,name='create_album'),
    path('album/favourite/<int:album_id>/',views.favouriteAlbum,name='album_favourite'),
    path('song/<str:filter_by>/',views.song,name='songs'),
    path('song/add/<int:album_id>',views.songCreate,name='create_song'),
    path('song/favourite/<int:song_id>/',views.favouriteSong,name='song_favourite'),
    path('album/<int:album_id>/delete_album/',views.deleteAlbum,name='delete_album'),
    path('song/<int:album_id>/delete_song/<int:song_id>/',views.deleteSong,name='delete_song'),
    path('register/',views.register,name='register'),
    path('login_user/',views.login_user,name='login_user'),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('lyrics/<int:song_id>', views.lyrics,name='lyrics')
]

music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from gaana import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homeView,name='home'),
    path('gaana/', include('gaana.urls')),
    path('blog/',include('blog.urls')),
    path('hots/',include('hots.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from datetime import date
# Create your models here.

class Blog(models.Model):
    blog_title=models.CharField(max_length=500)
    blog_image=models.FileField()
    description = models.TextField(max_length=2000, help_text="Enter you blog text here.")
    post_date = models.DateField(default=date.today)

    def __str__(self):
        return self.blog_title

blog/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields=['blog_title','blog_image','description']

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog
from .forms import BlogForm



IMAGE_FILE_TYPES=['png','jpg','jpeg']
# Create your views here.
def indexView(request):
    all_blogs=Blog.objects.order_by('-post_date')
    return render(request,'blog/index.html',{'all_blogs':all_blogs})

def detailView(request,blog_id):
    blog=get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/detail.html',{'blog':blog})


def create_blog(request):
    form=BlogForm(request.POST or None ,request.FILES or None)
    if form.is_valid():
        blog=form.save(commit=False)
        blog.blog_image=request.FILES['blog_image']
        file_type=blog.blog_image.url.split('.')[-1]
        file_type=file_type.lower()
        if file_type not in IMAGE_FILE_TYPES:
            content={'blog':blog,'form':form,'error_message':'Image file must be PNG,JPG or JPEG'}
            return render(request,'blog/form.html',content)
        else:
            blog.save()
            return render(request,'blog/detail.html',{'blog':blog})
    else:
        return render(request,'blog/form.html',{'form':form})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Blog{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" href="{% static 'gaana/style.css' %}"/> {#include ot after bootstrap otherwise we wont able to overwrite#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'gaana/js/main.js' %}"></script>
<style>
.header {

    text-align: center;
    background: #000000;
}
.navbar
{
    margin-bottom: 0px;
}
body {
    background:url("images/backblog.jpg");
}
</style>
</head>
<body>
{% load staticfiles%}
        <div class="header">
        <img src="{% static "gaana/images/logo5.jpg"%}">
        </div>
<nav class="navbar navbar-inverse"  style="background:#080808;">
    <div class="container-fluid">
        <!-- Header  here data-target is to target element ie where to use toggle button-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">afreen</a>
        </div>

        <!-- Items id since here we gonna use data-target feature and album_active block is for highlighing working page-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}" ><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'blog:index' %}"><span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span>&nbsp; All Blogs</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'gaana:index' %}" id="navBarSearchForm">
                <div class="form-group">
                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
              <button type="submit" class="btn btn-default" style="background:#080808; color:#ccc ">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'blog:create_blog' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Blog
                    </a>
                </li>
                <li class=""><a href="{% url 'blog:index' %}"><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span>&nbsp;Contact Us</a></li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-4 col-lg-4">
          <div class="panel panel-default" style="background-color:#080808b0; color:#e1d3c1">
              <div class="panel-body">
                  <a href="{% url 'blog:detail' blog.id %}">
                      {% if blog.blog_image %}
                          <img src="{{ blog.blog_image.url }}" class="img-responsive">
                      {% else %}
                          <h3>No image to display</h3>
                      {% endif %}
                  </a>
              </div>
          </div>
      </div>
      <div class="col-sm-8 col-md-8">
          <div class="panel panel-default"style="background-color:#080808b0; color:#e1d3c1">
              <div class="panel-body" >
                <h1>{{ blog.blog_title}}</h1>
                <p>{{blog.description}}</p>
                <h3>{{ blog.post_date}}</h3>
              </div>
            </div>
          </div>
        </div>
  {% endblock %}

blog/templates/blog/form.html
{% extends 'blog/base.html' %}
{% block title %}Add a New Blog{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default" style="background-color:#080808b0; color:#e1d3c1">
                <div class="panel-body">
                    <h3>Add a New Blog</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>
                                <label class="control-label col-sm-2" for="blog_title">{{ field.label_tag }}</label>
                                <div class="col-sm-10" style="color:#000000">{{ field }}</div>
                            </div>
                        {% endfor %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}My Blog{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}

<div class="w3-container w3-black" style="position:relative">

 <h1 class="w3-jumbo w3-text-white" style="text-shadow:1px 1px 0 #444">My Blog</h1>
</div>

<div class=" w3-animate-zoom" style="padding:20px 50px;
background-size:cover;">
{% if all_blogs %}
    {% for blog in all_blogs %}
    <div class="albums-container container-fluid">

        <!-- Albums -->
        <div class="row">
            <div class="col-sm-4 col-lg-4">
              <div class="panel panel-default" style="background-color:#080808b0; color:#e1d3c1">
                  <div class="panel-body">
                      <a href="{% url 'blog:detail' blog.id %}">
                          {% if blog.blog_image %}
                              <img src="{{ blog.blog_image.url }}" class="img-responsive">
                          {% else %}
                              <h3>No image to display</h3>
                          {% endif %}
                      </a>
                  </div>
              </div>
          </div>
          <div class="col-sm-8 col-md-8">
              <div class="panel panel-default"style="background-color:#080808b0; color:#e1d3c1">
                  <div class="panel-body" >
                    <h1>{{ blog.blog_title}}</h1>
                    <h3>{{ blog.post_date}}</h3>
                  </div>
                </div>
              </div>
            </div>
    {% endfor %}
{% else %}
<div class="col-sm-12">
    <br>
    <a href="{% url 'blog:create_blog' %}">
        <button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Blog
        </button>
    </a>
</div>
{% endif %}


</div>


{% endblock %}